"""cart table

Revision ID: 0a7b6dbf1a39
Revises: 0eff2f2d9d59
Create Date: 2019-12-05 12:40:39.947472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7b6dbf1a39'
down_revision = '0eff2f2d9d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('prod_id', sa.Integer(), nullable=False),
    sa.Column('prod_name', sa.String(length=64), nullable=True),
    sa.Column('prod_cost', sa.Integer(), nullable=True),
    sa.Column('prod_desc', sa.String(length=140), nullable=True),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('u_cart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['u_cart_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('prod_id')
    )
    op.create_index(op.f('ix_cart_prod_name'), 'cart', ['prod_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_prod_name'), table_name='cart')
    op.drop_table('cart')
    # ### end Alembic commands ###
