"""item count table

Revision ID: 26738dca689f
Revises: e70da1a978a9
Create Date: 2020-03-27 14:51:20.218235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26738dca689f'
down_revision = 'e70da1a978a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'item_page')
    op.add_column('user', sa.Column('token', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token')
    op.add_column('cart', sa.Column('item_page', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
