"""item count table

Revision ID: 443f7ef0eed7
Revises: 0cf749cd6620
Create Date: 2020-03-16 20:33:36.123041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443f7ef0eed7'
down_revision = '0cf749cd6620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_user_address', sa.String(length=84), nullable=True),
    sa.Column('order_item_detail', sa.JSON(), nullable=True),
    sa.Column('order_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_order_order_user_address'), 'order', ['order_user_address'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_order_user_address'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
