"""item count table

Revision ID: bfe3a45b545a
Revises: 72863516e8c6
Create Date: 2020-01-11 18:26:11.127939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe3a45b545a'
down_revision = '72863516e8c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subs', sa.Column('cart_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subs', 'cart_count')
    # ### end Alembic commands ###
