"""item count table

Revision ID: f1a9f702e7c5
Revises: 23fbe2b3cd9e
Create Date: 2020-01-12 17:13:00.127992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a9f702e7c5'
down_revision = '23fbe2b3cd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=64), nullable=True),
    sa.Column('brand_desc', sa.String(length=140), nullable=True),
    sa.Column('brand_filename', sa.String(), nullable=True),
    sa.Column('brand_url', sa.String(), nullable=True),
    sa.Column('brand_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_index(op.f('ix_brand_brand_name'), 'brand', ['brand_name'], unique=True)
    op.create_table('subs',
    sa.Column('subs_id', sa.Integer(), nullable=False),
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('cart_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['p_id'], ['cart.prod_id'], ),
    sa.ForeignKeyConstraint(['u_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('subs_id', 'u_id', 'p_id')
    )
    op.add_column('cart', sa.Column('buy_item', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('part_cost', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('part_desc', sa.String(length=140), nullable=True))
    op.add_column('cart', sa.Column('part_name', sa.String(length=64), nullable=True))
    op.add_column('cart', sa.Column('u_cart_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cart_part_name'), 'cart', ['part_name'], unique=True)
    op.drop_index('ix_cart_prod_name', table_name='cart')
    op.create_foreign_key(None, 'cart', 'user', ['u_cart_id'], ['id'])
    op.drop_column('cart', 'prod_name')
    op.drop_column('cart', 'user_id')
    op.drop_column('cart', 'prod_cost')
    op.drop_column('cart', 'prod_desc')
    op.add_column('user', sa.Column('item_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'item_count')
    op.add_column('cart', sa.Column('prod_desc', sa.VARCHAR(length=140), nullable=True))
    op.add_column('cart', sa.Column('prod_cost', sa.INTEGER(), nullable=True))
    op.add_column('cart', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('cart', sa.Column('prod_name', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_index('ix_cart_prod_name', 'cart', ['prod_name'], unique=1)
    op.drop_index(op.f('ix_cart_part_name'), table_name='cart')
    op.drop_column('cart', 'u_cart_id')
    op.drop_column('cart', 'part_name')
    op.drop_column('cart', 'part_desc')
    op.drop_column('cart', 'part_cost')
    op.drop_column('cart', 'buy_item')
    op.drop_table('subs')
    op.drop_index(op.f('ix_brand_brand_name'), table_name='brand')
    op.drop_table('brand')
    # ### end Alembic commands ###
