"""item count table

Revision ID: faf1efa15bfa
Revises: 7615be63381b
Create Date: 2020-03-16 18:18:53.415268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf1efa15bfa'
down_revision = '7615be63381b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('order_user_address', sa.String(length=84), nullable=True),
    sa.Column('order_item_detail', sa.String(), nullable=True),
    sa.Column('order_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_order_order_user_address'), 'order', ['order_user_address'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_order_user_address'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
