"""cart table

Revision ID: 5bc8ab4861a8
Revises: 728b7a407e29
Create Date: 2019-12-13 08:56:42.734290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc8ab4861a8'
down_revision = '728b7a407e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=64), nullable=True),
    sa.Column('brand_desc', sa.String(length=140), nullable=True),
    sa.Column('brand_filename', sa.String(), nullable=True),
    sa.Column('brand_url', sa.String(), nullable=True),
    sa.Column('brand_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_index(op.f('ix_brand_brand_name'), 'brand', ['brand_name'], unique=True)
    op.add_column('cart', sa.Column('buy_item', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'user', ['u_cart_id'], ['id'])
    op.drop_column('cart', 'prod_name')
    op.drop_column('cart', 'prod_cost')
    op.drop_column('cart', 'user_id')
    op.drop_column('cart', 'prod_desc')
    op.add_column('user', sa.Column('item_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'item_count')
    op.add_column('cart', sa.Column('prod_desc', sa.VARCHAR(length=140), nullable=True))
    op.add_column('cart', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('cart', sa.Column('prod_cost', sa.INTEGER(), nullable=True))
    op.add_column('cart', sa.Column('prod_name', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'buy_item')
    op.drop_index(op.f('ix_brand_brand_name'), table_name='brand')
    op.drop_table('brand')
    # ### end Alembic commands ###
