"""item count table

Revision ID: 6efd300ddc87
Revises: 9d07dd767ca3
Create Date: 2020-03-22 16:49:52.496148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6efd300ddc87'
down_revision = '9d07dd767ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('item_page', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'item_page')
    # ### end Alembic commands ###
