"""cart table

Revision ID: 728b7a407e29
Revises: 4e68556a4e57
Create Date: 2019-12-06 12:52:35.947815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728b7a407e29'
down_revision = '4e68556a4e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cart', 'user', ['u_cart_id'], ['id'])
    op.drop_column('cart', 'prod_cost')
    op.drop_column('cart', 'image_url')
    op.drop_column('cart', 'user_id')
    op.drop_column('cart', 'image_filename')
    op.drop_column('cart', 'prod_desc')
    op.drop_column('cart', 'prod_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('prod_name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('cart', sa.Column('prod_desc', sa.VARCHAR(length=140), nullable=True))
    op.add_column('cart', sa.Column('image_filename', sa.VARCHAR(), nullable=True))
    op.add_column('cart', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('cart', sa.Column('image_url', sa.VARCHAR(), nullable=True))
    op.add_column('cart', sa.Column('prod_cost', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    # ### end Alembic commands ###
