"""cart table

Revision ID: 7fb742a1185b
Revises: a364e98441b3
Create Date: 2019-12-06 12:35:38.455499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb742a1185b'
down_revision = 'a364e98441b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('prod_id', sa.Integer(), nullable=False),
    sa.Column('part_name', sa.String(length=64), nullable=True),
    sa.Column('part_cost', sa.Integer(), nullable=True),
    sa.Column('part_desc', sa.String(length=140), nullable=True),
    sa.Column('u_cart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['u_cart_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('prod_id')
    )
    op.create_index(op.f('ix_cart_part_name'), 'cart', ['part_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_part_name'), table_name='cart')
    op.drop_table('cart')
    # ### end Alembic commands ###
