"""item count table

Revision ID: 88140c86a544
Revises: 032abd44fb7a
Create Date: 2020-01-12 13:44:11.904586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88140c86a544'
down_revision = '032abd44fb7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('brand',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=64), nullable=True),
    sa.Column('brand_desc', sa.String(length=140), nullable=True),
    sa.Column('brand_filename', sa.String(), nullable=True),
    sa.Column('brand_url', sa.String(), nullable=True),
    sa.Column('brand_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_index(op.f('ix_brand_brand_name'), 'brand', ['brand_name'], unique=True)
    op.create_table('cart',
    sa.Column('prod_id', sa.Integer(), nullable=False),
    sa.Column('part_name', sa.String(length=64), nullable=True),
    sa.Column('part_cost', sa.Integer(), nullable=True),
    sa.Column('part_desc', sa.String(length=140), nullable=True),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('u_cart_id', sa.Integer(), nullable=True),
    sa.Column('buy_item', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['u_cart_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('prod_id')
    )
    op.create_index(op.f('ix_cart_part_name'), 'cart', ['part_name'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('subs',
    sa.Column('subs_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('prod_id', sa.Integer(), nullable=True),
    sa.Column('cart_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['prod_id'], ['cart.prod_id'], ),
    sa.PrimaryKeyConstraint('subs_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subs')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('followers')
    op.drop_index(op.f('ix_cart_part_name'), table_name='cart')
    op.drop_table('cart')
    op.drop_index(op.f('ix_brand_brand_name'), table_name='brand')
    op.drop_table('brand')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
