"""cartt table

Revision ID: a364e98441b3
Revises: 0a7b6dbf1a39
Create Date: 2019-12-06 10:17:36.643032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a364e98441b3'
down_revision = '0a7b6dbf1a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('part_cost', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('part_desc', sa.String(length=140), nullable=True))
    op.add_column('cart', sa.Column('part_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_cart_part_name'), 'cart', ['part_name'], unique=True)
    op.drop_index('ix_cart_prod_name', table_name='cart')
    op.drop_column('cart', 'prod_cost')
    op.drop_column('cart', 'image_filename')
    op.drop_column('cart', 'prod_name')
    op.drop_column('cart', 'prod_desc')
    op.drop_column('cart', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('image_url', sa.VARCHAR(), nullable=True))
    op.add_column('cart', sa.Column('prod_desc', sa.VARCHAR(length=140), nullable=True))
    op.add_column('cart', sa.Column('prod_name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('cart', sa.Column('image_filename', sa.VARCHAR(), nullable=True))
    op.add_column('cart', sa.Column('prod_cost', sa.INTEGER(), nullable=True))
    op.create_index('ix_cart_prod_name', 'cart', ['prod_name'], unique=1)
    op.drop_index(op.f('ix_cart_part_name'), table_name='cart')
    op.drop_column('cart', 'part_name')
    op.drop_column('cart', 'part_desc')
    op.drop_column('cart', 'part_cost')
    # ### end Alembic commands ###
