"""item count table

Revision ID: e70da1a978a9
Revises: 6efd300ddc87
Create Date: 2020-03-27 14:51:05.462049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70da1a978a9'
down_revision = '6efd300ddc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'item_page')
    op.add_column('user', sa.Column('token', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token')
    op.add_column('cart', sa.Column('item_page', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
