"""cart table

Revision ID: 4e68556a4e57
Revises: 7fb742a1185b
Create Date: 2019-12-06 12:52:16.932183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e68556a4e57'
down_revision = '7fb742a1185b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('part_cost', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('part_desc', sa.String(length=140), nullable=True))
    op.add_column('cart', sa.Column('part_name', sa.String(length=64), nullable=True))
    op.add_column('cart', sa.Column('u_cart_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cart_part_name'), 'cart', ['part_name'], unique=True)
    op.drop_index('ix_cart_prod_name', table_name='cart')
    op.create_foreign_key(None, 'cart', 'user', ['u_cart_id'], ['id'])
    op.drop_column('cart', 'user_id')
    op.drop_column('cart', 'image_url')
    op.drop_column('cart', 'image_filename')
    op.drop_column('cart', 'prod_cost')
    op.drop_column('cart', 'prod_desc')
    op.drop_column('cart', 'prod_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('prod_name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('cart', sa.Column('prod_desc', sa.VARCHAR(length=140), nullable=True))
    op.add_column('cart', sa.Column('prod_cost', sa.INTEGER(), nullable=True))
    op.add_column('cart', sa.Column('image_filename', sa.VARCHAR(), nullable=True))
    op.add_column('cart', sa.Column('image_url', sa.VARCHAR(), nullable=True))
    op.add_column('cart', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_index('ix_cart_prod_name', 'cart', ['prod_name'], unique=1)
    op.drop_index(op.f('ix_cart_part_name'), table_name='cart')
    op.drop_column('cart', 'u_cart_id')
    op.drop_column('cart', 'part_name')
    op.drop_column('cart', 'part_desc')
    op.drop_column('cart', 'part_cost')
    # ### end Alembic commands ###
