pipeline {
    agent any
    parameters {
        choice(
            choices: ['create' , 'destroy'],
            description: '',
            name: 'REQUESTED_ACTION')
    }	

    stages{

		stage('Deploying Infra on AWS') {

				when {
					  expression { params.REQUESTED_ACTION == 'create' }
				}	
			
			steps {
			sh "terraform init terraform-infra/; terraform apply -auto-approve terraform-infra/ "
			}

		
		}
	
		stage('Destroy Infra on AWS') {

				when {
					  expression { params.REQUESTED_ACTION == 'destroy' }
				}
			steps {
			sh "terraform init terraform-infra/; terraform destroy -auto-approve terraform-infra/"
			}	
			
		}	
	}
}
