pipeline {
    agent any
    parameters {
        choice(
            choices: ['create' , 'destroy'],
            description: '',
            name: 'REQUESTED_ACTION')
    }	

    stages{

		stage('Deploying Infra on AWS') {

				when {
					  expression { params.REQUESTED_ACTION == 'create' }
				}	
			
			steps {
			sh "cd terraform-infra"
			sh "terraform init; terraform apply -auto-approve "
			}

		
		}
}
}	
